### ISSUE TITLE
Linked categories with a description prevents URL generating for search results items

### ISSUE THREAD

**Issue by abohntek** [teaminmedias-pluswerk/ke_search#366] opened 2020-08-13 13:21 UTC
we had the problem that some news didn´t had the title linked to their detail view in the search result view. Their url value was always empty. We figured out that those news hat categories selected which had under Option->Description in the category edit view in the backend a value inserted. After removing the description value the ke_search was able to render the correct link for the news title in the search result. May this also is an issue for pages with such selected categories, but this we didn´t test.

**Comment by christianbltr** [comment] 2020-10-09 11:43
Unfortunately I was not able to reproduce this issue.

This is what I did
* Created a category "News cat 1"
* Gave that category a description
* Created a news record and assigned that category
* Started the indexer

In the frontend the news record is linked to the given detail view page.

Could please describe the steps how to re-produce the issue on your side?

Tested on
* TYPO3 10.4.9
* ke_search master
* news 8.4.1

**Comment by christianbltr** [comment] 2020-10-30 11:02
I recently had the following case:

There was a single_pid set in the category, but that page had been deleted. But ke_search still used the this page as a result page for news with this category. After saving the category again, the single_pid field would be empty, because the page did not exist and the correct target page would be used.

Maybe it was the same in your case. Simply saving the category record again then would have solved the issue.

This is now fixed in ke_search, it will check if the single_pid really is reachable.

Since I'm not able to reproduce the issue otherwise I'm closing this.

**Closed as completed by christianbltr** 2020-10-30 11:02 UTC
