### ISSUE TITLE
Scheduler task not working

### ISSUE THREAD

**Issue by pduersteler** [teaminmedias-pluswerk/ke_search#52] opened 2016-07-06 10:13 UTC
The scheduler task provided in the scheduler BE module is not working. When setting it up, it yields an error telling me "The selected task class could not be found.".

Not sure if it depends on #45

**Comment by christianbltr** [comment] 2016-07-06 12:06
I did a quick test with ke_search current master on a TYPO3 7.6.9 system and could not reproduce this. 

Could you provide more information on how to reproduce this?

**Comment by pduersteler** [comment] 2016-07-07 07:53
I was working on tag v2.2.1 as the current master was otherwise broken (see #53 ).

**Comment by christianbltr** [comment] 2016-07-07 11:36
This issue seemed to be only the case in an environment not installed with composer.

After applying https://github.com/teaminmedias-pluswerk/ke_search/pull/54 this seems to be fixed in current master.

I tested this in a 7.6.9 installation not installed with composer.

**Closed as completed by christianbltr** 2016-07-07 11:36 UTC
