### ISSUE TITLE
Indexer Configuration tt_address: indexPids

### ISSUE THREAD

**Issue by epx-dasc** [teaminmedias-pluswerk/ke_search#446] opened 2022-09-15 15:20 UTC
Hi together,

I am using ke_search 4.5.0 in TYPO3 11.5.16 with tt_address 6.1.0.

The indexer tt_address does not find the **indexPids** and always returns an empty array when indexing:
ke_search/Classes/Indexer/Types/TtAddress.php
Line 59

result: Indexer Configuration tt_address  | No address records found!

Without the `$this->getPidList` function it works:

```
        $indexPids[] = $this->indexerConfig['startingpoints_recursive'];
        $indexPids[] = $this->indexerConfig['sysfolder'];
```

Can you please check this and fix it.

Many thanks in advance

**Comment by christianbltr** [comment] 2022-09-16 08:01
Hey,

I tested this (also with ke_search 4.5.0, tt_address 6.1.0 and TYPO3 11.5.16) and could not reproduce the issue.

Did you use the field "Pages/folders recursive" or "Single folders"? If you used "Pages/folders recursive" could you try to use "Single folders" instead?

Also please note that the ke_search repository has moved and the new issue tracker can be found at https://github.com/tpwd/ke_search/issues. I'm closing this here. Please open a new issue over there if the problem still exists. Thank you!

**Closed as completed by christianbltr** 2022-09-16 08:01 UTC

**Comment by epx-dasc** [comment] 2022-09-22 12:50
Hi Christian,

thanks for your quick feedback.

The cause is now found, the tt_address records are only indexed if the folder with the records is set to 'Include in Search'.

greetings
