### ISSUE TITLE
Fatal error: TYPO3\CMS\Scheduler\Scheduler::cleanExecutionArrays(): The script tried to execute a method or access a property of an incomplete object. 

### ISSUE THREAD

**Issue by plojewski** [teaminmedias-pluswerk/ke_search#384] opened 2020-12-07 10:06 UTC
Hi, Typo3 9.5.23, ke_search 3.3.1.
When I click on Scheduler there is an error:

`
Fatal error: TYPO3\CMS\Scheduler\Scheduler::cleanExecutionArrays(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;tx_kesearch_indexertask&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /xxx/typo3/sysext/scheduler/Classes/Scheduler.php on line 125
`

Could you help please?

**Comment by christianbltr** [comment] 2020-12-11 09:37
Unfortunately I cannot reproduce this in my test environment using TYPO3 9.5.23, ke_search 3.3.1, installed with composer.

Did you use composer to install the environment?

**Comment by upputter** [comment] 2021-02-24 08:53
Same problem here after upgrade from TYPO3 v8.7.32 (ke_search v2.8.3) to TYPO3 v9.5.24 (ke_search v3.4.2).

We could remove the error message by deleting the ke_search scheduler task from the table `tx_scheduler_task`.

**Comment by christianbltr** [comment] 2021-03-05 09:54
@upputter Does this problem come up again after re-adding a new scheduler task? Or did it only occur once after upgrading?

@plojewski Did you also upgrade from TYPO3 8 to 9? Does deleting the scheduler task and re-adding it in TYPO3 9 help?

**Comment by christianbltr** [comment] 2021-11-05 10:25
I'm closing this here. Feel free to open another issue at https://github.com/tpwd/ke_search/issues it is still an issue for you.

**Closed as completed by christianbltr** 2021-11-05 10:25 UTC
Labels: needs feedback
