### ISSUE TITLE
ke_search url routeEnhancers

### ISSUE THREAD

**Issue by LPGGNecromant** [teaminmedias-pluswerk/ke_search#320] opened 2019-10-10 09:52 UTC
How to route with ke_search and config.yaml?

Is there even an controller for it?

**Comment by rowild** [comment] 2019-11-09 07:54
A much requested topic, already when there was realurl... teaminmedias: You already promised various times that you are going to provide example snippets. Please live up to your promises! Thank you!

**Comment by martingebhardt** [comment] 2019-11-12 10:22
Yes, that's also a big issue for me, I also need valid urls.

**Comment by DavidBruchmann** [comment] 2020-04-07 13:09
duplicate of #279

**Comment by christianbltr** [comment] 2020-12-04 13:11
Closing this as a duplicate of #279, please have a look at https://github.com/teaminmedias-pluswerk/ke_search/issues/279#issuecomment-738775432

**Closed as completed by christianbltr** 2020-12-04 13:11 UTC
