### ISSUE TITLE
indexer ignores pages without content [ doktype = 3 ]

### ISSUE THREAD

**Issue by xerc** [teaminmedias-pluswerk/ke_search#204] opened 2018-04-09 16:29 UTC
https://github.com/teaminmedias-pluswerk/ke_search/blob/59065ffbec47d5db50c1dc67faef273782c4b215/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php#L420-L422
https://github.com/teaminmedias-pluswerk/ke_search/blob/59065ffbec47d5db50c1dc67faef273782c4b215/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php#L467-L470

**Comment by christianbltr** [comment] 2021-02-19 08:51
It is by design that pages with doktype=3 won't be indexed by default.
You can adjust this setting in the indexer configuration (see screenshot).
So I'm closing this.

![Auswahl_029](https://user-images.githubusercontent.com/11410553/108481116-10f4b480-7298-11eb-8120-d6081a3c38b6.png)

**Closed as completed by christianbltr** 2021-02-19 08:51 UTC
