### ISSUE TITLE
Pagination doesn't work properly 

### ISSUE THREAD

**Issue by timofo** [teaminmedias-pluswerk/ke_search#313] opened 2019-08-27 09:49 UTC
Hello. I am using ke_search 3.0.4 and TYPO3 9.5.9. I think there is a bug in pagination. 
If i have 10 results and 5 per site, then it shows 
1, 2, 3, 4, 5 (next site) 6, 7, 8, 9, 10.  
But if i say f.e. 4 results per site, then it shows 
1, 2, 3, 4, (next site) 5, 6, (next site) 9, 10. 
Its missing 7 and 8 on second page. 
The same with 3 per page. I got 
1, 2, 3 (next site) 4, 5, 6, (next site) "nothing", (next site) 10. 
Its missing 7, 8 and 9 now.

**Comment by pfaffenrodt** [comment] 2019-09-06 13:29
Hello @timofo ,

we had an similar Issue.

We solved it by removing the "L" parameter from the search form.

```
<f:if condition="{lparam}">
    <input type="hidden" name="L" value="{lparam}" />
</f:if>
```

Default language was fine. only translations did not work properly.
Typo3 9 doesn't use L parameter anymore.

**Comment by timofo** [comment] 2019-09-06 13:49
I have no "L" parameter in the search form. :-(

**Comment by alexanderstier** [comment] 2019-09-06 13:55
We have an issue regarding the same problem.
Setting the value to 12 results per page only shows 10 results in the list.

We also have no "L" parameter in the form.

ke_search 3.0.4 and TYPO3 9.5.9

**Comment by kiefer79** [comment] 2019-09-06 14:12
I think this regards to https://github.com/teaminmedias-pluswerk/ke_search/issues/298

This is fixed in master and will make it into the next release.

**Comment by timofo** [comment] 2019-09-06 14:26
But i have less then 10 per page. See my example in the first message.

**Comment by christianbltr** [comment] 2019-10-31 16:22
I could not reproduce this issue on my test environment.
Setting "Results per page" to "4" gives me results 1 to 4 on the first page and 5 to 8 on the second page.
Could you provide a link to an example?
Do you extend or modify ke_search in any way?

**Comment by timofo** [comment] 2019-11-04 13:16
I have now updated the extension to 3.0.5. Now it seems to work. It might also have something to do with the bug ""resultsPerPage" not working if >10".

**Comment by christianbltr** [comment] 2019-11-07 09:08
Thanks for the feedback.

**Closed as completed by christianbltr** 2019-11-07 09:08 UTC
