### ISSUE TITLE
Repetitive result and missing page

### ISSUE THREAD

**Issue by SirNovi** [teaminmedias-pluswerk/ke_search#72] opened 2016-11-07 18:42 UTC
Following the quick installation, I ran a little test to determine if ke_search was for me. On my first search, which was for a single word which appears on 2 pages and in 1 file, I got erroneous results. 

The file appeared twice and one of the two pages did not appear at all in the search results. The page that didn't appear includes the word itself but it also includes the link to the file that appeared. The file is being linked to in two different content elements on said page. 

After removing one of the links to the file, it only appears once in the search results but the page itself does not appear.

I am using the default indexer for pages.

Thanks and Greetings
Novi

**Comment by christianbltr** [comment] 2016-11-08 08:34
Hello,

it's difficult to really track down a possible error based on this description. Could you provide a link where to test this behaviour? 

Or could provide an instruction how to exactly reproduce this possible error?

Greetings,

Christian

**Comment by SirNovi** [comment] 2016-11-08 10:54
I'm afraid I can't provide a link at this moment. For testing purposes, I went to another page with a linked file and created a new content element and linked to said file again. Then I emptied the index and rebuilt it and voilá: the file appears twice in the search results. 

I would expect that there would be some kind of measurement to prevent files and pages from appearing more than once in a single search result list.

I have yet to determine why that one page did not appear in the results and if the two issues are related. But fixing this one issue would be a good step already.

Cheers, 
Novi

**Comment by christianbltr** [comment] 2021-04-16 08:24
I tested this in the current version of ke_search and could not reproduce the issue, so I'm closing this.

If you still get duplicate results for the same file with the current version of ke_search please feel free to re-open this issue.

**Closed as completed by christianbltr** 2021-04-16 08:24 UTC
