### ISSUE TITLE
PHP Warning: in_array() expects parameter 2 to be array, string given in ke_search/Classes/lib/class.tx_kesearch_filters.php line 119

### ISSUE THREAD

**Issue by vmans** [teaminmedias-pluswerk/ke_search#157] opened 2017-09-18 11:45 UTC
PHP Warning: in_array() expects parameter 2 to be array, string given in /home/sites/.../typo3conf/ext/ke_search/Classes/lib/class.tx_kesearch_filters.php line 119

reference fo instance [(https://stackoverflow.com/questions/32559674/in-array-expects-parameter-2-to-be-array-string-given-in)]

So perhaps change line 119:

`$isInArray = in_array($this->pObj->piVars['filter'][$filter['uid']], $option['tag']);`

into:

`$isInArray = in_array($this->pObj->piVars['filter'][$filter['uid']], (array)$option['tag']);`

**Comment by hotbytes** [comment] 2017-09-21 09:33
Hi, the Problem is that the parameters must be switched. The function in_array expects the first parameter to be the needle and the second to be the array.

```php
$this->pObj->piVars['filter'][$filter['uid']]
```

is the array and 

```php
$option['tag']
```

is a string, so the line must be

```php
$isInArray = in_array($option['tag'], $this->pObj->piVars['filter'][$filter['uid']]);
```

The function in_array is used in multiple files. Maybe every call should be reviewed.

Thanks for fixing

**Comment by christianbltr** [comment] 2017-10-04 09:43
Fixed in current master. 
Will be in next version after 2.5.0.
Bug has been introduced in https://github.com/teaminmedias-pluswerk/ke_search/pull/138.

**Closed as completed by christianbltr** 2017-10-04 09:43 UTC

**Comment by ucking44** [comment] 2019-08-07 10:33
Please I need your help on this

ErrorException
Warning: in_array() expects parameter 2 to be array, string given
/app/Modules/Base/Traits/Acl.php in App\Modules\Base\Traits\Acl::can at line 37
    }
    public static function can($permissions)
    {
        if ((Auth::user()->hasRole('employee-payroll')) && in_array('payroll', $permissions)) {
            return true;
        }
        if ((Auth::user()->hasRole('employee-ims')) && in_array('ims', $permissions)) {
            return true;
