### ISSUE TITLE
error by indexing pages

### ISSUE THREAD

**Issue by p-view** [teaminmedias-pluswerk/ke_search#448] opened 2022-12-07 10:26 UTC
become in typo3 11.5 ke_search 4.5.1:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT pages.*, GROUP_CONCAT(CONCAT("#", tx_kesearch_filteroptions.tag, "#")) as tags FROM `pages`, `tx_kesearch_filteroptions` WHERE (pages.uid IN (565,1000195,1000196,1000197,1000198,1000199,1000201,1000202,1000203,1000204,1000205,1000206,1000207,1000208,1000209,1000210,1000211,1000212,1000229) AND pages.tx_kesearch_tags <> "" AND FIND_IN_SET(tx_kesearch_filteroptions.uid, pages.tx_kesearch_tags)) AND (((`pages`.`deleted` = 0) AND (`tx_kesearch_filteroptions`.`deleted` = 0)) AND ((`pages`.`hidden` = 0) AND (`tx_kesearch_filteroptions`.`hidden` = 0))) GROUP BY `pages`.`uid`': 'typo3_2022.pages.pid' isn't in GROUP BY

**Comment by christianbltr** [comment] 2022-12-10 15:47
What database are you using and in which version?
Could you explain a bit more how to reproduce this issue?

**Comment by p-view** [comment] 2022-12-12 07:58
i use MariaDB 10.1.48
the problem comes from indexerBase.php #250
        $tagQuery = $queryBuilder
            ->add('select', $fields)
            ->from('pages')
            ->from('tx_kesearch_filteroptions')
            ->add('where', $where)
            **->groupBy('pages.uid')**
            ->execute();

solutions by google keeps me this: "In mysql array, set strict => false to disable MySQL's strict mode"
But for me is not possible to configurate this.

**Comment by christianbltr** [comment] 2023-01-13 11:14
This error only occurs when sql_mode ONLY_FULL_GROUP_BY is set.
This is now fixed in version 4.6.2.
Thanks for reporting.

Please use https://github.com/tpwd/ke_search/issues for reporting further issues because that's the official issue tracker.

**Closed as completed by christianbltr** 2023-01-13 11:14 UTC
