### ISSUE TITLE
ViewHelper requires $resetFilters as array

### ISSUE THREAD

**Issue by elKruso** [teaminmedias-pluswerk/ke_search#391] opened 2021-01-29 15:02 UTC
Hello there,

after updating to v3.4.0 right away (customer wanting pretty url) i ran into an typo3 error.
Turns out the viewHelper "kesearch:link", as mentioned in the documentation, requires "resetFilters" given as an argument.

After some research an a lot of error messages complaining that in SearchHelper.php Line 386 the $resetFilter is not an array, i found the fix in my template:
<kesearch:link keepPiVars="1" uriOnly="1" resetFilters="{0: 0}" />

you may set the default to being an array. Until then, i suggest you document my "dirty" fix :)
Thanks for the extension.

**Comment by crealistiques** [comment] 2021-02-02 18:30
Hello, I can confirm this issue caused by a wrong default value of type string here https://github.com/teaminmedias-pluswerk/ke_search/blob/1e24ffedb0c218da28cfb008e00560b9c602a213/Classes/ViewHelpers/LinkViewHelper.php#L39

Imho it should be `$resetFilters = $this->arguments['resetFilters'] ?? [];`

Thanks a lot!

**Comment by christianbltr** [comment] 2021-02-05 09:18
Thanks for reporting, this has been fixed and will be in version 3.4.1

Fix is in
https://github.com/teaminmedias-pluswerk/ke_search/commit/410fbc26e064c97aa87e229e02c54af755636d63

**Closed as completed by christianbltr** 2021-02-05 09:18 UTC
