### ISSUE TITLE
Null pointer exception during indexing

### ISSUE THREAD

**Issue by r3h6** [teaminmedias-pluswerk/ke_search#221] opened 2018-07-26 07:32 UTC
```
Call to a member function getForLocalProcessing() on null 

Error thrown in file
/var/www/web/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php in line 708.

18 tx_kesearch_indexer_types_page::indexFiles(array, array, "", "#file#")

/var/www/web/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php:
00487:                 // index the files found
00488:                 if (!$pageAccessRestrictions['hidden']) {
00489:                     $this->indexFiles($fileObjects, $ttContentRow, $pageAccessRestrictions['fe_group'], $tags);
00490:                 }
```
Followed for setup your "Quickstart" guide.

**Comment by SicorDev** [comment] 2018-10-15 06:55
@teaminmedias-pluswerk We can reproduce this issue with 2.8 and TYPO3 8 LTS.

The issue occures if a null pointer follows a valid FileReference. (`$fileObjects`)
In this case the working `$fileObject` sets `$isInList`. The next `$fileObject` is a null pointer and fails the first condition, but enters the second condition, because `$isInList` is still set from the previous `$fileObject`.

https://github.com/teaminmedias-pluswerk/ke_search/blob/442ea9a6a7c13030d42c9e4a3c5ab65aa90fbc0b/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php#L694-L708

If you reset the variable `$isInList` or initialize it at the beginning it works as intended:
```php
            foreach ($fileObjects as $fileObject) {
                $isInList = false;
                if ($fileObject instanceof FileInterface) {
                    $isInList = \TYPO3\CMS\Core\Utility\GeneralUtility::inList(
                        $this->indexerConfig['fileext'],
                        $fileObject->getExtension()
                    );
                } else {
                    $this->addError('Could not index file in content element #' . $ttContentRow['uid'] . ' (no file object).');
                }
                
                ...
        }
```

**Comment by christianbltr** [comment] 2018-11-28 10:30
Thanks. Fixed in current master and compat9 branch.
Will be in version 2.8.1 and 3.0.0.

**Closed as completed by christianbltr** 2018-11-28 10:30 UTC
