### ISSUE TITLE
Sorting do not work

### ISSUE THREAD

**Issue by p-view** [teaminmedias-pluswerk/ke_search#286] opened 2019-04-11 08:53 UTC
when i have two Serachforms  (Header & Result) than do not work Sorting.
thx for the great extension

**Comment by DavidBruchmann** [comment] 2020-04-07 06:35
two different forms are not supported.
It might be possible to make it working somehow i.e. by including content (the search forms and result plugins) from different pages, but I see that the url-parameters are not made to address distinguished plugins. So any solution for it - if possible at all - requires a very nifty setup.
The problem is very old, I addressed it in pi_base-extensions too, programmed even a solution for it but related to extbase it will be probably much harder.  
So currently the expected answer by devs is **won't be fixed**.

**Comment by christianbltr** [comment] 2021-08-27 06:33
That's correct, it's not possible to have two search forms on the same page and there are currently no plans to add support for this.

**Closed as completed by christianbltr** 2021-08-27 06:33 UTC
